use std::fs::DirEntry;
use std::io::Write;

use srtemplate::SrTemplate;

use crate::error::Error;
use crate::metadata::Config;

/// Write a legal PKGBUILD to some `Write` instance (a `File` in this case).
pub fn pkgbuild<T>(
    ctx: SrTemplate,
    mut file: T,
    config: &Config,
    sha256: &str,
    license: &[DirEntry],
) -> Result<(), Error>
where
    T: Write,
{
    let package = &config.package;
    let authors = package
        .authors
        .iter()
        .map(|a| format!("# Maintainer: {}", a))
        .collect::<Vec<_>>()
        .join("\n");
    let source = package
        .git_host()
        .unwrap_or_default()
        .source(&ctx, &config.package)?;

    writeln!(file, "{}", authors)?;
    writeln!(file, "#")?;
    writeln!(
        file,
        "# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur"
    )?;
    writeln!(file)?;
    writeln!(file, "pkgname={}", ctx.render(&package.template_name())?)?;
    writeln!(file, "pkgver={}", package.version)?;
    writeln!(file, "pkgrel=1")?;
    writeln!(file, "pkgdesc=\"{}\"", package.description)?;
    writeln!(file, "url=\"{}\"", package.homepage)?;
    writeln!(file, "license=(\"{}\")", package.license)?;
    writeln!(file, "arch=(\"x86_64\")")?;
    writeln!(file, "provides=(\"{}\")", package.name)?;
    writeln!(file, "conflicts=(\"{}\")", package.name)?;

    if let Some(metadata) = package.metadata.as_ref() {
        writeln!(file, "{}", metadata)?;
    }

    writeln!(file, "source=(\"{}\")", source)?;
    writeln!(file, "sha256sums=(\"{}\")", sha256)?;
    writeln!(file)?;
    writeln!(file, "package() {{")?;
    writeln!(
        file,
        "    find . -name '{}' -type f -executable -exec install -Dm755 {{}} -t \"$pkgdir/usr/bin\" \\;",
        config.binary_name()
    )?;

    writeln!(file, "    mkdir -p \"$pkgdir/usr/share/licenses/$pkgname\"")?;

    if !license.is_empty() {
        writeln!(file, "\n    # Instalación opcional de licencias")?;
        writeln!(file, "    if [[ -d \"$srcdir\" ]]; then")?;
        writeln!(
            file,
            "        mkdir -p \"$pkgdir/usr/share/licenses/$pkgname\""
        )?;
        writeln!(file, "        pushd \"$srcdir\" >/dev/null")?;

        for lic in license {
            let file_name = lic.file_name();
            let file_name = file_name.to_string_lossy();
            writeln!(
                file,
                "        if [[ -f \"{}\" && -s \"{}\" ]]; then",
                file_name, file_name
            )?;
            writeln!(
                file,
                "            install -Dm644 \"{}\" \"$pkgdir/usr/share/licenses/$pkgname/{}\"",
                file_name, file_name
            )?;
            writeln!(file, "        else")?;
            writeln!(
                file,
                "            echo \"Warning: License file '{}' missing or empty - skipping\" >&2",
                file_name
            )?;
            writeln!(file, "        fi")?;
        }

        writeln!(file, "        popd >/dev/null")?;
        writeln!(file, "    else")?;
        writeln!(
            file,
            "        echo \"Warning: No license files found in $srcdir\" >&2"
        )?;
        writeln!(file, "    fi")?;
    } else {
        writeln!(
            file,
            "    echo \"Notice: No license files included in this package\" >&2"
        )?;
    }

    writeln!(file, "}}")?;
    Ok(())
}
